
#pragma once

typedef enum {
  MENU_NULL = 0,
  MENU_MAIN,
  MENU_SETTINGS,
  MENU_SETTINGS_CONTROLS,
  MENU_SETTINGS_ADV_CONTROLS,
  MENU_SETTINGS_AUDIO,
  MENU_CREDITS,
  MENU_COUNT
} MenuEnums;
