
#pragma once

typedef enum {
  ALIGNMENT_CENTER = 0b1111,
  ALIGNMENT_LEFT = 0b0001,
  ALIGNMENT_TOP = 0b0010,
  ALIGNMENT_RIGHT = 0b0100,
  ALIGNMENT_BOTTOM = 0b1000,

  ALIGNMENT_TOP_LEFT = ALIGNMENT_TOP | ALIGNMENT_LEFT,
  ALIGNMENT_TOP_RIGHT = ALIGNMENT_TOP | ALIGNMENT_RIGHT,
  ALIGNMENT_BOTTOM_LEFT = ALIGNMENT_BOTTOM | ALIGNMENT_LEFT,
  ALIGNMENT_BOTTOM_RIGHT = ALIGNMENT_BOTTOM | ALIGNMENT_RIGHT
} Alignment;

typedef struct {
  int x, y;
} Position;
