
#pragma once

typedef enum {
  BORDER_LEFT = 1,
  BORDER_TOP = 1 << 1,
  BORDER_RIGHT = 1 << 2,
  BORDER_BOTTOM = 1 << 3,

  BORDER_TOP_LEFT = BORDER_TOP | BORDER_LEFT,
  BORDER_TOP_RIGHT = BORDER_TOP | BORDER_RIGHT,
  BORDER_BOTTOM_LEFT = BORDER_BOTTOM | BORDER_LEFT,
  BORDER_BOTTOM_RIGHT = BORDER_BOTTOM | BORDER_RIGHT,

  BORDER_ALL = BORDER_LEFT | BORDER_TOP | BORDER_RIGHT | BORDER_BOTTOM
} BorderSides;
